import "./globals.css";
import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Jesus Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
